version: "3"
services: 
    ms_sql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports: 
            - 1433:1433
        environment: 
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
        volumes: 
            - ./ms_sql/data/:/var/opt/mssql/data/
            - ./ms_sql/log/:/var/opt/mssql/log/
        networks: 
            - default
    apache:
        build:
            context: .
            dockerfile: ./Dockerfile.apache
        ports:
            - 80:80
        volumes: 
            - ./www:/var/www/html/
            - ./logs:/var/log/apache2/
        networks: 
            - default
        