version: "3"
services: 
    db:
        image: mariadb
        ports: 
            - 3306:3306
        environment:  
            MYSQL_ROOT_PASSWORD: test
        volumes: 
            - ./dbInit:/docker-entrypoint-initdb.d
            - ./mysql:/var/lib/mysql
        networks: 
            - default
    apache:
        build:
            context: .
            dockerfile: ./Dockerfile.apache
        ports:
            - 80:80
        volumes: 
            - ./www:/var/www/html/
            - ./logs:/var/log/apache2/
        networks: 
            - default
        