version: "3"
services: 
    ms_sql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment: 
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
        volumes: